name = "hellobusan"
compatibility_date = "2026-09-01"
pages_build_output_dir = "./dist"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "hellobusan"
database_id = "76019a8a-7d52-4603-a3b5-33176b42c2fd"
